# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc224eb650734dff370cd36816975346"
application_url = "https://major-predicted-namibia-stage.trycloudflare.com"
embedded = true
name = "won-app"
handle = "won-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dropsiping-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_orders,read_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://major-predicted-namibia-stage.trycloudflare.com/auth/callback",
  "https://major-predicted-namibia-stage.trycloudflare.com/auth/shopify/callback",
  "https://wonport-be.onrender.com/shopifyAccount/callback",
  "https://major-predicted-namibia-stage.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
